### ISSUE TITLE
New Build Website

### ISSUE THREAD

**Issue by jimthedj65** [diodechain/website#14]
I have carefully gone through all the dependencies 
nvm ls
->       v6.5.0
        v8.10.0
       v12.16.1
        v14.4.0
         system
default -> 6.5.0 (-> v6.5.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v14.4.0) (default)
stable -> 14.4 (-> v14.4.0) (default)
lts/* -> lts/gallium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.19.2 (-> N/A)
lts/gallium -> v16.15.0 (-> N/A)

npm version
{ 'sera-onepage': '1.1.0',
  npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.81',
  zlib: '1.2.8' }

_**and installed everything as follows:**_ 

`Install NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

To check that nvm is installed, type nvm --version. If you get a version number back like 0.35.3, then you know nvm was successfully installed.

Restart your terminal for your changes to take effect.

Install NodeJS
Next, let's install Nodejs version 6.5.0

Simply run nvm install 6.5.0 .

You can use a similar command to install any version of node you want, for example nvm install 12.18.1.

This command automatically installs nodejs as well as the latest npm version which is at  v6.14.5.

If you ever need to switch node versions, you can simply run nvm use <version-number> , for example **nvm use v12.18.1.**

To list the different node versions you have installed with nvm, run **nvm ls.**

Install Nodesource
Run the command below to tell Ubuntu that we want to install the Nodejs
package from nodesource.

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

NB that v14.4.0 is the latest version of Node but doesn't currently have LTS - long term support provided for it. To install the latest version of Node with LTS, change 14 in the command above to 12.

You may be prompted to enter the password for your root user. Enter that and hit enter/return.

Install NodeJS
Once we're done setting up Nodesource, we can now install Nodejs v14.4.
Run sudo apt-get install -y nodejs.

Once we're done, we can check that we have the latest version of Node installed.
Simply type nodejs -v into your terminal and it should return v14.4.0.

You should have npm automatically installed at this point. To check what npm version you have, run **npm version.** If you do not get an object that includes the latest version of npm at 6.14.5, { npm: '6.14.5' }, then you can update npm manually by running the following command:

npm install -g npm@latest.

If you run into any issues with npm being unable to update because it's not installed, you can install npm first by using sudo apt-get install -y npm, then run the command above to update it.

For certain npm packages to run, we also need to run the command below
sudo apt install build-essential.`

All seems to go fine with a few warnings, when I start ./run I gt an error
`Now using node v6.5.0 (npm v3.10.3)
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/home/ubuntu/website/node_modules/engine.io/build/server.js:173
    async handshake(transportName, req, closeConnection) {
          ^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/website/node_modules/engine.io/build/engine.io.js:5:18)
    at Module._compile (module.js:556:32)`

any help appreciated.

**Comment by jimthedj65** [comment]
I forgot to add running it on ubuntu 18.04

**Comment by jimthedj65** [comment]
ran the install on a mac build and it seemed to go much better when running Jekyll build I get an error (I get this far on ubuntu now)

jekyll build
/Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated concurrent-ruby 1.1.10, but your Gemfile requires concurrent-ruby 1.1.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:25:in `block in setup'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/spec_set.rb:136:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/spec_set.rb:136:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:24:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler/runtime.rb:24:in `setup'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.13/lib/bundler.rb:151:in `setup'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by jimthedj65** [comment]
prepending bundle exec on mac allows me to get it running on localhost
